apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: database-cluster
  namespace: production
spec:
  instances: 2

  storage:
    size: 10Gi

  resources:
    requests:
      cpu: "1"
      memory: 2Gi
    limits:
      cpu: "2"
      memory: 4Gi
  
  
