apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
  namespace: production
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/add-base-url: "true"  # Add base URL
spec:
  tls:
    - secretName: local-production-tls
      hosts:
        - local.production
  rules:
    - host: local.production
      http:
        paths:
          # Static content for frontend/UI
          - path: /
            pathType: Prefix
            backend:
              service:
                name: qa-ui-service
                port:
                  number: 3000

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-api
  namespace: production
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/add-base-url: "true"  # Add base URL
spec:
  tls:
    - secretName: local-production-tls
      hosts:
        - local.production
  rules:
    - host: local.production
      http:
        paths:
          - path: /api(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: qa-api-service
                port:
                  number: 7777


---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-websocket
  namespace: production
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/add-base-url: "true"  # Add base URL
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-connect-timeout: '3600'
    nginx.ingress.kubernetes.io/websocket-services: "websocket-service"
spec:
  tls:
    - secretName: local-production-tls
      hosts:
        - local.production
  rules:
  - host: local.production
    http:
      paths:
      - path: /ws
        pathType: Prefix
        backend:
          service:
            name: websocket-service
            port:
              number: 7788

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-api-llm
  namespace: production
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/add-base-url: "true"  # Add base URL
spec:
  tls:
    - secretName: local-production-tls
      hosts:
        - local.production
  rules:
    - host: local.production
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: llm-api-service
                port:
                  number: 7000