version: "3.4"

volumes:
  astro_node_modules:

services:
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - programming-api
    ports:
      - 7800:7800

  programming-api:
    build: programming-api
    image: programming-api
    restart: "no"
    volumes:
      - ./programming-api/:/app
      - ./app-cache/:/app-cache
    expose:
      - 7777
    depends_on:
      - database
      - flyway
      - redis
    env_file:
      - project.env
    deploy:
      replicas: 2

  programming-ui:
    build: programming-ui
    image: programming-ui
    restart: "no"
    volumes:
      - ./programming-ui/:/app
      - astro_node_modules:/app/node_modules
    depends_on:
      - programming-api
    expose:
      - 3000

  grader-api:
    build: grader-api
    image: grader-api
    restart: "no"
    env_file:
        - project.env
    depends_on:
      - programming-api
    volumes:
      - ./grader-api/:/app
      - ./app-cache/:/app-cache
      - "/var/run/docker.sock:/var/run/docker.sock"
    expose:
      - 7000

  websocket:
    build: ./websocket
    ports:
      - "7788:7788"
    depends_on:
      - redis

  database:
    container_name: database-server
    image: postgres:14.1
    restart: "no"
    env_file:
        - project.env

  flyway:
    image: flyway/flyway:9.11.0-alpine
    depends_on:
      - database
    volumes:
      - ./flyway/sql/:/flyway/sql
    command: -connectRetries=60 -baselineOnMigrate=true migrate
    env_file:
      - project.env

  e2e-playwright:
    entrypoint: "/bin/true"
    build: e2e-playwright
    image: e2e-playwright
    network_mode: host
    depends_on:
      - nginx
    volumes:
      - ./e2e-playwright/tests:/e2e-playwright/tests
      
  redis:
    image: redis:latest
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    expose:
      - 6379