version: "3.4"

volumes:
  astro_node_modules:

services:
  programming-ui:
    build: 
      context: programming-ui
      dockerfile: Dockerfile.prod
    image: programming-ui-prod
    restart: "on-failure"
    expose:
      - 3000
    depends_on:
      - programming-api
    deploy:
      restart_policy:
        condition: on-failure
        delay: "5s"
        max_attempts: 5
        window: "30s"

  redis:
    image: redis:latest
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    expose:
      - 6379

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.prod.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - programming-api
    ports:
      - 7800:7800

  programming-api:
    build: 
      context: programming-api
      dockerfile: Dockerfile.prod
    image: programming-api-prod
    restart: "on-failure"
    expose:
      - 7777
    depends_on:
      - database
      - flyway
      - redis
    env_file:
      - project.env
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
        delay: "5s"
        max_attempts: 5
        window: "30s"

  grader-api:
    build: grader-api
    image: grader-api
    restart: "no"
    env_file:
        - project.env
    depends_on:
      - programming-api
      - redis
    volumes:
      - ./grader-api/:/app
      - ./app-cache/:/app-cache
      - "/var/run/docker.sock:/var/run/docker.sock"
    expose:
      - 7000
    deploy:
      replicas: 2
    command: ["nodemon", "--watch", ".", "worker.js"]

  database:
    container_name: database-server
    image: postgres:14.1
    restart: unless-stopped
    volumes:
      - ./production-database-data:/var/lib/postgresql/data
    env_file:
        - project.env

  flyway:
    image: flyway/flyway:9.11.0-alpine
    depends_on:
      - database
    volumes:
      - ./flyway/sql/:/flyway/sql
    command: -connectRetries=60 -baselineOnMigrate=true migrate
    env_file:
      - project.env
    profiles:
      - migrate

  pgadmin:
    image: dpage/pgadmin4:6.20
    env_file:
      - project.env
    depends_on:
      - database
    profiles:
      - pgadmin

  websocket:
    build: ./websocket
    ports:
      - "7788:7788"
    depends_on:
      - redis
    volumes:
      - ./websocket/:/app  

  e2e-playwright:
    entrypoint: "/bin/true"
    build: e2e-playwright
    image: e2e-playwright
    network_mode: host
    depends_on:
      - nginx
      - database
      - flyway
      - programming-api
      - programming-ui
      - grader-api
      - websocket
      - redis
    volumes:
      - ./e2e-playwright/tests:/e2e-playwright/tests
      
